version: '3.7'
services:
  web:
    image: pfadiolten-home:dev
    build:
      context: .
      args:
        - http_proxy
    command: sh -c "ruby ./bin/webpack --webpack --colors --progress & bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - PFADIOLTEN_OSM_ACCESS_TOKEN
      - PFADIOLTEN_INSTAGRAM_CLIENT_ID
      - PFADIOLTEN_INSTAGRAM_CLIENT_SECRET
      - PFADIOLTEN_INSTAGRAM_ACCESS_TOKEN

      - http_proxy
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - .:/pfadiolten-home
      - gems:/usr/local/bundle
      - node_modules:/pfadiolten-home/node_modules
    depends_on:
      - db
    tmpfs:
      - /pfadiolten-home/log
      - /pfadiolten-home/tmp
      - /pfadiolten-home/public/packs

  db:
    image: postgres:11
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: pfadiolten-home.data
  gems:
    name: pfadiolten-home.gems
  node_modules:
    name: pfadiolten-home.node_modules