version: '3.7'
services:
  web:
    image: pfadiolten-home:dev
    build:
      context: .
      args:
        - http_proxy
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development

      - PFADIOLTEN_OSM_ACCESS_TOKEN
      - PFADIOLTEN_INSTAGRAM_CLIENT_ID
      - PFADIOLTEN_INSTAGRAM_CLIENT_SECRET
      - PFADIOLTEN_INSTAGRAM_ACCESS_TOKEN

      - http_proxy
    volumes:
      - gems:/usr/local/bundle
      - .:/pfadiolten-home
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name: pfadiolten-home.data
  gems:
    name: pfadiolten-home.gems