default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: devpass
  pool: 5

development:
  <<: *default
  database: pfadiolten_home-development

test:
  <<: *default
  database: pfadiolten_home-test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>