default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: pfadiolten_home-development

test:
  <<: *default
  database: pfadiolten_home-test