social:
  mail:         "info@pfadiolten.ch"
  it:           "it@pfadiolten.ch"
  instagram:    "https://instagram.com/pfadiolten"
  instagram_id: 4547751471
  facebook:     "https://facebook.com/pfadiolten"
  github:       "https://github.com/pfadiolten/pfadiolten-home"

external:
  oetiker:
    homepage: "https://www.oetiker.ch"

contacts:
  people:
    - title: "Abteilungsleiter"
      name:  "Daniel von Atzigen v/o Abou"
      phone: "+41 79 727 19 98"
      mail:  "abou@pfadiolten.ch"

    - title: "Abteilungsleiterin"
      name:  "Anouk Bachofner v/o Tunaya"
      phone: "+41 79 353 36 13"
      mail:  "tunaya@pfadiolten.ch"

    - title: "Vereinspräsident"
      name:  "Elias Niklaus v/o Tiki"
      phone: "+41 76 320 71 56"
      mail: "tiki@pfadiolten.ch"

  banking:
    address:  "Raiffeisenbank Olten, 4603 Olten"
    iban:     "CH22 8080 8008 5506 3235 2"
    receiver: "Pfadi Olten, 4600 Olten"

locations:
  maps:
    - address:
        street: "Rötzmattweg 119"
        city: "Olten"
        zip_code: "4600"
      coordinates:
        x: 47.34481
        y: 7.89599

  infos:
    renting: "Aus organisatorischen Gründen kann das Heim momentan leider nicht vermietet werden."

