name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/prod.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pfadiolten-home:latest
            ghcr.io/${{ github.repository_owner }}/pfadiolten-home:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
